name: Debug Secrets
on: [push]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          echo "NPM_TOKEN length: ${#NPM_TOKEN}"
          echo "SEMANTIC_RELEASE_TOKEN length: ${#SEMANTIC_RELEASE_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      - name: Test NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
